version: "3.8"
services:
  client_dev:
    build: ./client
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /home/app/client
    volumes:
      - ./client:/home/app/client
  server_dev:
    build: ./server
    command: sh -c "npm install && npm run dev"
    environment:
      DB_CONNECTION_STRING: postgres://postgres:parola@db:5432/todo-case-db
    ports:
      - 5000:5000
    working_dir: /home/app/server
    volumes:
      - ./server:/home/app/server
    depends_on:
      - db
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: todo-case-db

    volumes:
      - ./server/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    ports:
      - 5432:5432
